name: CI
on: [push]
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - ruby-version: 3.0.2
            gemfile: gemfiles/Gemfile.rails.7.0
          - ruby-version: 2.7.4
            gemfile: gemfiles/Gemfile.rails.6.1
          - ruby-version: 2.6.8
            gemfile: gemfiles/Gemfile.rails.6.0
          - ruby-version: 2.5.9
            gemfile: gemfiles/Gemfile.rails.5.2
    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - name: Run tests
        run: bundle exec rake
